// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as k8s from "@pulumi/kubernetes";
import * as inputs from "../../types/input";
import * as outputs from "../../types/output";
import * as utilities from "../../utilities";

import {ObjectMeta} from "../../meta/v1";

export class Telemetry extends pulumi.CustomResource {
    /**
     * Get an existing Telemetry resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, opts?: pulumi.CustomResourceOptions): Telemetry {
        return new Telemetry(name, undefined as any, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'kubernetes:telemetry.istio.io/v1alpha1:Telemetry';

    /**
     * Returns true if the given object is an instance of Telemetry.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is Telemetry {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === Telemetry.__pulumiType;
    }

    public readonly apiVersion!: pulumi.Output<"telemetry.istio.io/v1alpha1">;
    public readonly kind!: pulumi.Output<"Telemetry">;
    public readonly metadata!: pulumi.Output<k8s.types.output.meta.v1.ObjectMeta>;
    /**
     * Telemetry configuration for workloads. See more details at: https://istio.io/docs/reference/config/telemetry.html
     */
    public readonly spec!: pulumi.Output<outputs.telemetry.v1alpha1.TelemetrySpec>;
    public readonly status!: pulumi.Output<{[key: string]: any}>;

    /**
     * Create a Telemetry resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args?: TelemetryArgs, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (!opts.id) {
            resourceInputs["apiVersion"] = "telemetry.istio.io/v1alpha1";
            resourceInputs["kind"] = "Telemetry";
            resourceInputs["metadata"] = args ? args.metadata : undefined;
            resourceInputs["spec"] = args ? args.spec : undefined;
            resourceInputs["status"] = args ? args.status : undefined;
        } else {
            resourceInputs["apiVersion"] = undefined /*out*/;
            resourceInputs["kind"] = undefined /*out*/;
            resourceInputs["metadata"] = undefined /*out*/;
            resourceInputs["spec"] = undefined /*out*/;
            resourceInputs["status"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(Telemetry.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * The set of arguments for constructing a Telemetry resource.
 */
export interface TelemetryArgs {
    apiVersion?: pulumi.Input<"telemetry.istio.io/v1alpha1">;
    kind?: pulumi.Input<"Telemetry">;
    metadata?: pulumi.Input<ObjectMeta>;
    /**
     * Telemetry configuration for workloads. See more details at: https://istio.io/docs/reference/config/telemetry.html
     */
    spec?: pulumi.Input<inputs.telemetry.v1alpha1.TelemetrySpecArgs>;
    status?: pulumi.Input<{[key: string]: any}>;
}
